# Appending sls- to the service name to differentiate
# resources created by Serverless framework vs Terraform

service: sls-hello-world

provider:
  name: aws
  runtime: nodejs12.x
  region: "eu-west-2"
  stage: ${opt:stage, "development"}

functions:
  healthz:
    handler: ./healthz/healthz.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

# DO not need this plugin since we will be compiling before
# the deployment step
plugins:
  - serverless-plugin-typescript
