name: My Lambda

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build -> Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        working-directory: infrastructure
        run: terraform init
          -var stage="development"
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}"
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        working-directory: infrastructure
        run: terraform apply -auto-approve
          -var stage="development"
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}"
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Deploy Cloud Functions
        working-directory: functions
        run: npm i && npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CI_DEVELOPER_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_DEVELOPER_SECRET_ACCESS_KEY }}
